services:

  caddy:
    container_name: formio-proxy
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "${EXTERNAL_FORMIO_PORT}:80"
    volumes:
      - ./volumes/caddy/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config

volumes:
  caddy-data:
  caddy-config:
